'use client';

import { useMemo, useState } from 'react';
import { Activity, AlertTriangle, ArrowDownToLine, ArrowUpFromLine, Battery, Bell, Calculator, Check, ChevronDown, CircleGauge, Database, Download, Grid2X2, HelpCircle, MapPin, Menu, Scale, Search, ShieldCheck, SlidersHorizontal, Sun, X, Zap } from 'lucide-react';
import { Area, AreaChart, CartesianGrid, Legend, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { creditAllocations, energyRequests, hourlyFlow, incomingSources, infrastructure, outgoingAllocations } from '../src/data/mockCouncilData';
import PriorityAllocation from './PriorityAllocation';
import './styles.css';

const sections = [
  ['overview','System overview',Grid2X2],['incoming','Verified exports',ArrowDownToLine],['outgoing','Support allocations',ArrowUpFromLine],
  ['requests','Support requests',ShieldCheck],['priority','Priority allocation',Scale],['pool','Contribution pool',Battery],['credits','Credit allocations',Calculator],['telemetry','Grid telemetry',Activity],
];

function Status({value}){return <span className={`cd-status cd-status--${value.toLowerCase().replaceAll(' ','-')}`}><i/>{value}</span>}
function Metric({label,value,detail,icon:Icon,tone='blue'}){return <article className="cd-metric"><div className={`cd-metric-icon ${tone}`}><Icon/></div><div><span>{label}</span><strong>{value}</strong><p>{detail}</p></div></article>}
function Health({value}){return <div className="cd-health"><div><span style={{width:`${value}%`}} className={value<70?'bad':value<90?'warn':''}/></div><strong>{value}%</strong></div>}

function CouncilTable({type}){
 const incoming=type==='incoming'; const data=incoming?incomingSources:outgoingAllocations;
 const [query,setQuery]=useState(''); const filter='All';
 const shown=useMemo(()=>data.filter(row=>Object.values(row).join(' ').toLowerCase().includes(query.toLowerCase())&&(filter==='All'||(row.status||row.type)===filter)),[data,query,filter]);
 return <section className="cd-panel cd-table-panel"><div className="cd-panel-head"><div><p className="cd-kicker">Program registry</p><h2>{incoming?'Verified export records':'Support allocations'}</h2><p>{incoming?'Verified exports counted toward the SARGE contribution pool.':'Current and scheduled support allocations. kWh-equivalent values are accounting units, not physical electricity delivery.'}</p></div><button className="cd-secondary"><Download/> Export CSV</button></div><div className="cd-table-tools"><label><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search ID, property or suburb"/></label><button className="cd-filter"><SlidersHorizontal/> {filter}<ChevronDown/></button><span>{shown.length} records</span></div><div className="cd-table-scroll"><table><thead><tr>{incoming?<><th>Source</th><th>Location</th><th>Capacity</th><th>Export now</th><th>Verified today</th><th>Data health</th><th>Status</th><th>Last update</th></>:<><th>Allocation</th><th>Household</th><th>Location</th><th>Allocated equivalent</th><th>Period total</th><th>Program</th><th>Contribution pool</th><th>Status</th></>}</tr></thead><tbody>{shown.map(row=>incoming?<tr key={row.id}><td><strong>{row.id}</strong><small>{row.property}<br/>{row.type}</small></td><td><MapPin/>{row.suburb}</td><td>{row.capacity} kW</td><td><strong>{row.current} kW</strong></td><td>{row.today} kWh</td><td><Health value={row.health}/></td><td><Status value={row.status}/></td><td>{row.updated}</td></tr>:<tr key={row.id}><td><strong>{row.id}</strong></td><td>{row.household}</td><td><MapPin/>{row.suburb}</td><td><strong>{row.current} kWh-eq</strong></td><td>{row.today} kWh-eq</td><td>{row.allocation}</td><td>{row.source}</td><td><Status value={row.status}/></td></tr>)}</tbody></table></div></section>
}

function Requests(){const [rows,setRows]=useState(energyRequests);const validate=id=>setRows(x=>x.map(r=>r.id===id?{...r,status:'Validated'}:r));return <section className="cd-panel"><div className="cd-panel-head"><div><p className="cd-kicker">Automated workflow oversight</p><h2>Incoming support requests</h2><p>The allocation service validates support requests automatically. Council officers can inspect evidence and intervene where needed.</p></div><span className="cd-info"><ShieldCheck/> {rows.filter(r=>r.status==='Validated').length} automatically validated</span></div><div className="cd-request-list">{rows.map(r=><article key={r.id}><div className={`cd-priority ${r.priority.toLowerCase()}`}>{r.priority}</div><div className="cd-request-main"><div><strong>{r.id}</strong><span>{r.household} · {r.suburb}</span></div><p>{r.reason}</p></div><div><span>Requested equivalent</span><strong>{r.requested} kWh-eq</strong></div><div><span>Assessment period</span><strong>{r.window}</strong></div><div><span>Model confidence</span><strong>{r.confidence}%</strong></div><Status value={r.status}/>{r.status==='Pending review'?<button onClick={()=>validate(r.id)} className="cd-primary"><Check/> Validate</button>:<button className="cd-text">View evidence</button>}</article>)}</div></section>}

function Pool(){return <><div className="cd-metrics"><Metric label="Verified contribution total" value="12.48 MWh" detail="Across 438 contributors" icon={Database}/><Metric label="Available allocation units" value="3.84 MWh-eq" detail="30.8% of recorded contributions" icon={Zap} tone="green"/><Metric label="Protected reserve" value="1.26 MWh-eq" detail="Held outside the normal allocation" icon={Battery} tone="purple"/><Metric label="Assessment runway" value="18.4 hr" detail="At predicted support demand" icon={CircleGauge} tone="orange"/></div><section className="cd-pool-grid"><div className="cd-panel"><div className="cd-panel-head"><div><h2>24-hour contribution outlook</h2><p>Forecast verified contributions, support demand and protected reserve.</p></div><span className="cd-forecast">Updated 2 min ago</span></div><div className="cd-forecast-chart">{[68,74,82,91,88,79,65,48,38,31,28,35].map((v,i)=><div key={i}><span style={{height:`${v}%`}}/><small>{i%2===0?`${i+8}:00`:''}</small></div>)}</div><div className="cd-legend"><span><i className="supply"/>Forecast contribution units</span><span><i className="demand"/>Predicted support demand: 2.96 MWh-eq</span></div></div><div className="cd-panel cd-reserve"><h2>Reserve policy</h2><div className="cd-ring"><strong>33%</strong><span>of allocation units</span></div><dl><div><dt>Minimum reserve</dt><dd>1.10 MWh-eq</dd></div><div><dt>Current reserve</dt><dd>1.26 MWh-eq</dd></div><div><dt>Headroom</dt><dd className="positive">+160 kWh-eq</dd></div></dl><button className="cd-secondary">Review reserve settings</button></div></section></>}

function Credits(){return <section className="cd-panel cd-table-panel"><div className="cd-panel-head"><div><p className="cd-kicker">August 2026 cycle</p><h2>Owner credit allocations</h2><p>MVP calculation: 1 verified contributed kWh equals 1 Sarge Credit.</p></div><button className="cd-primary"><Calculator/> Run allocation cycle</button></div><div className="cd-credit-summary"><div><span>Credits calculated</span><strong>18,426</strong></div><div><span>Owners included</span><strong>438</strong></div><div><span>Adjustments for review</span><strong>3</strong></div><div><span>Calculation integrity</span><strong>100%</strong></div></div><div className="cd-table-scroll"><table><thead><tr><th>Owner</th><th>Type</th><th>Location</th><th>Verified contribution</th><th>Rate</th><th>Base credits</th><th>Adjustment</th><th>Status</th></tr></thead><tbody>{creditAllocations.map(r=><tr key={r.owner}><td><strong>{r.owner}</strong></td><td>{r.type}</td><td>{r.suburb}</td><td>{r.contributed} kWh</td><td>{r.rate}:1</td><td><strong>{r.credits}</strong></td><td>{r.adjustment?`+${r.adjustment}`:'—'}</td><td><Status value={r.status}/></td></tr>)}</tbody></table></div><div className="cd-formula"><Calculator/><div><strong>Calculation policy v1.0</strong><code>credits = min(pledged_kwh, verified_spare_kwh) × 1</code></div><button className="cd-text">View calculation audit</button></div></section>}

function Telemetry(){return <><div className="cd-alert"><AlertTriangle/><div><strong>1 interface requires monitoring</strong><span>Grid Interface G-04 is operating within tolerance but showing sustained high load.</span></div><button>View alert</button></div><section className="cd-panel"><div className="cd-panel-head"><div><p className="cd-kicker">Live telemetry</p><h2>Local hubs and grid interfaces</h2><p>Operational health, load and connection quality across the Sarge network.</p></div><span className="cd-live"><i/> Live · 15 sec refresh</span></div><div className="cd-hub-grid">{infrastructure.map(h=><article key={h.name}><div className="cd-hub-top"><div className="cd-hub-icon"><Activity/></div><Status value={h.status}/></div><h3>{h.name}</h3><p>{h.kind}</p><Health value={h.health}/><dl><div><dt>Current load</dt><dd>{h.load}%</dd></div><div><dt>Voltage</dt><dd>{h.voltage}</dd></div><div><dt>Frequency</dt><dd>{h.frequency}</dd></div><div><dt>Telemetry latency</dt><dd>{h.latency}</dd></div></dl></article>)}</div></section></>}

function Overview(){return <><div className="cd-metrics"><Metric label="Verified exports now" value="2.48 MW" detail="+8.2% from yesterday" icon={Sun} tone="green"/><Metric label="Support allocated" value="1.72 MWh-eq" detail="Across 126 households" icon={ArrowUpFromLine}/><Metric label="Allocation pool" value="3.84 MWh-eq" detail="18.4 hours forecast runway" icon={Battery} tone="purple"/><Metric label="Data health" value="96.2%" detail="4 healthy · 1 monitor" icon={Activity} tone="orange"/></div><div className="cd-overview-grid"><section className="cd-panel cd-flow-panel"><div className="cd-panel-head"><div><h2>Contribution and support accounting</h2><p>Verified export records and support-allocation equivalents today.</p></div><span className="cd-live"><i/> Live</span></div><div className="cd-flow-chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={hourlyFlow}><defs><linearGradient id="in" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#16a36a" stopOpacity=".24"/><stop offset="1" stopColor="#16a36a" stopOpacity="0"/></linearGradient><linearGradient id="out" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#1672e8" stopOpacity=".18"/><stop offset="1" stopColor="#1672e8" stopOpacity="0"/></linearGradient></defs><CartesianGrid vertical={false} stroke="#e7ebef"/><XAxis dataKey="time" axisLine={false} tickLine={false}/><YAxis axisLine={false} tickLine={false}/><Tooltip/><Legend/><Area type="monotone" dataKey="incoming" name="Verified exports" stroke="#139665" fill="url(#in)" strokeWidth={2}/><Area type="monotone" dataKey="outgoing" name="Support allocations" stroke="#1672e8" fill="url(#out)" strokeWidth={2}/></AreaChart></ResponsiveContainer></div></section><section className="cd-panel cd-ops"><div className="cd-panel-head"><div><h2>Operations attention</h2><p>Items requiring council visibility.</p></div></div><div className="cd-ops-item warn"><AlertTriangle/><div><strong>Grid Interface G-04</strong><span>Sustained load at 88%</span></div><button>Review</button></div><div className="cd-ops-item"><ShieldCheck/><div><strong>2 requests awaiting review</strong><span>Both within policy tolerance</span></div><button>Open</button></div><div className="cd-ops-item"><Calculator/><div><strong>3 credit adjustments</strong><span>August cycle closes in 4 days</span></div><button>Review</button></div></section></div><div className="cd-two-tables"><CouncilTable type="incoming"/><Requests/></div></>}

function CouncilView({view}){if(view==='incoming')return <CouncilTable type="incoming"/>;if(view==='outgoing')return <CouncilTable type="outgoing"/>;if(view==='requests')return <Requests/>;if(view==='priority')return <PriorityAllocation/>;if(view==='pool')return <Pool/>;if(view==='credits')return <Credits/>;if(view==='telemetry')return <Telemetry/>;return <Overview/>}

export default function CouncilDashboard(){const [view,setView]=useState('overview');const [mobile,setMobile]=useState(false);const current=sections.find(x=>x[0]===view);return <main className="council-app"><aside className={mobile?'open':''}><div className="cd-brand"><div><img src="/assets/figma/sarge-lightning-mark.png" alt=""/><strong>Sarge</strong></div><span>Council operations</span><button onClick={()=>setMobile(false)}><X/></button></div><nav>{sections.map(([id,label,Icon])=><button className={view===id?'active':''} onClick={()=>{setView(id);setMobile(false)}} key={id}><Icon/><span>{label}</span>{id==='requests'&&<b>2</b>}</button>)}</nav><div className="cd-side-foot"><HelpCircle/><div><strong>Operations support</strong><span>System status: Operational</span></div></div></aside><div className="cd-main"><header><button className="cd-mobile-menu" onClick={()=>setMobile(true)}><Menu/></button><div><p>Wollongong community energy</p><h1>{current[1]}</h1></div><div className="cd-header-actions"><label><Search/><input placeholder="Search network"/></label><button className="cd-icon-button"><Bell/><i/></button><button className="cd-user"><span>JM</span><div><strong>J. Martin</strong><small>Council operator</small></div><ChevronDown/></button></div></header><div className="cd-content"><div className="cd-system-bar"><div><span className="cd-live"><i/> System operational</span><span>Saturday, 22 August 2026 · 6:54 PM</span></div><div><span>Data latency: <strong>18 sec</strong></span><span>Automation: <strong>Active</strong></span></div></div><CouncilView view={view}/></div></div></main>}
