'use client';
/* eslint-disable @next/next/no-img-element */

import { BrowserRouter, Navigate, NavLink, Route, Routes, useNavigate } from 'react-router-dom';
import { ArrowRight, Building2, Check, ChevronLeft, Download, FileText, Home, Menu, Users, X, Zap } from 'lucide-react';
import { Bar, BarChart, CartesianGrid, Legend, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { useState, useSyncExternalStore } from 'react';
import { energyHistory, rewards, user, calculateContribution, calculateSargeCredits } from '../src/data/mockEnergyData';
import CouncilDashboard from '../../council-frontend/app/CouncilDashboard';

const Button = ({ children, variant = 'dark', className = '', ...props }) => <button className={`button button--${variant} ${className}`} {...props}>{children}</button>;
const heroAssets = {
  background: '/assets/figma/hero-sun-shadow-bg.jpg',
  mark: '/assets/figma/sarge-logo-mark.png',
  divider: '/assets/figma/logo-divider.svg',
  family: '/assets/figma/sarge-family-solar-crop.png',
};
const donorPropertyTypes = [['Home',Home],['Apartment Building',Building2],['Business',Building2],['Council Property',Building2]];

function Logo() { return <NavLink className="logo" to="/overview" aria-label="Sarge home"><Zap size={24} fill="currentColor" strokeWidth={3}/><strong>Sarge</strong></NavLink>; }

function Navbar() {
  const [open, setOpen] = useState(false);
  const links = [['/overview','Overview'],['/contribute','Contribute'],['/rewards','Rewards'],['/reports','Reports']];
  return <header className="nav-wrap"><nav className="navbar" aria-label="Main navigation"><Logo/><div className={`nav-links ${open ? 'is-open' : ''}`}>{links.map(([to,label]) => <NavLink key={to} to={to} onClick={()=>setOpen(false)}>{label}</NavLink>)}<a className="contact-mobile" href="mailto:hello@sarge.community">Contact Us</a></div><a className="button button--dark contact" href="mailto:hello@sarge.community">Contact Us</a><button className="menu" onClick={()=>setOpen(!open)} aria-expanded={open} aria-label="Toggle menu">{open?<X/>:<Menu/>}</button></nav></header>;
}

function Shell({ children, title, eyebrow }) { return <><Navbar/><main className="page"><div className="page-title">{eyebrow && <p className="eyebrow">{eyebrow}</p>}<h1>{title}</h1></div>{children}</main></>; }

function EnergyFlow({ compact = false }) {
  const steps = [
    ['Generated',160,'Total solar produced','generated'],
    ['Used',74,'By my property','used'],
    ['Spare energy',86,'Verified from connected data','spare'],
    ['Contributed',85,'Shared with the community pool','contributed'],
  ];
  return <div className={`energy-flow ${compact?'energy-flow--compact':''}`} aria-label="160 kilowatt hours generated, 74 used, 86 spare, 85 contributed">{steps.map(([label,value,caption,type],i)=><div className={`energy-step ${type}`} key={label}><span className="step-index">0{i+1}</span><p>{label}</p><strong>{value}<small> kWh</small></strong><span>{caption}</span>{i<steps.length-1 && <ArrowRight className="flow-arrow" aria-hidden="true"/>}</div>)}</div>;
}

function ReportGenerator({ inline = false }) {
  const [period,setPeriod]=useState('This month'); const [generated,setGenerated]=useState(false);
  const download=()=>{const rows=['Metric,Value','Solar generated,160 kWh','Property consumption,74 kWh','Spare energy,86 kWh','Energy contributed,85 kWh','Sarge Credits earned,85','Households supported,4','Estimated community benefit,$26']; const blob=new Blob([rows.join('\n')],{type:'text/csv'}); const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download='sarge-energy-report.csv'; a.click(); URL.revokeObjectURL(a.href)};
  return <section className={`report-card ${inline?'report-card--inline':''}`}><div className="report-icon"><FileText/></div><p className="eyebrow">Reports</p><h2>Your Energy Report</h2><p>See where your solar went and the impact it created.</p><div className="segmented" aria-label="Report period">{['This month','Last 3 months','Last 6 months','Custom'].map(x=><button key={x} className={period===x?'active':''} onClick={()=>{setPeriod(x);setGenerated(false)}}>{x}</button>)}</div>{generated?<div className="report-preview"><div><span>Generated</span><strong>160 kWh</strong></div><div><span>Used</span><strong>74 kWh</strong></div><div><span>Spare</span><strong>86 kWh</strong></div><div><span>Contributed</span><strong>85 kWh</strong></div><div><span>Credits earned</span><strong>85</strong></div><div><span>Households supported</span><strong>4</strong></div><div className="benefit"><span>Estimated community benefit</span><strong>$26</strong></div></div>:<div className="report-placeholder"><span>{period}</span><div className="report-line"/><div className="report-line short"/><p>Your report will turn your energy data into a simple, downloadable summary.</p></div>}<Button onClick={()=>generated?download():setGenerated(true)}>{generated?<><Download size={18}/> Download report</>:<>Generate report <ArrowRight size={18}/></>}</Button></section>;
}

function Overview() {
  return <Shell title="Your Sarge Overview" eyebrow={`Hi, ${user.firstName}!`}><div className="overview-grid"><section className="overview-left"><h2>My Sarge</h2><div className="credit-card"><span>Current balance</span><strong>85</strong><h3>Sarge Credits</h3><p>+24 this month</p><NavLink className="button button--light" to="/rewards">Use my credits <ArrowRight size={18}/></NavLink></div><div className="impact-note"><Users/><p>Your energy supported <strong>4 households</strong> this month.</p></div></section><ReportGenerator inline/><section className="energy-panel"><p className="eyebrow">August 2026</p><h2>My Energy</h2><EnergyFlow/><div className="still-available"><span>Still available</span><strong>1 kWh</strong></div></section></div></Shell>;
}

function Contribute() {
 const spare=12; const [mode,setMode]=useState('all'); const [custom,setCustom]=useState(12); const [done,setDone]=useState(false); const pledge=mode==='all'?12:mode==='half'?6:Number(custom)||0; const actual=calculateContribution(pledge,spare);
 const confirm=()=>{localStorage.setItem('sargeContribution',JSON.stringify({donor_id:'D001',donor_type:'household',suburb:'Dapto',generated_kwh:26,consumed_kwh:14,verified_spare_kwh:12,pledged_kwh:pledge,contributed_kwh:actual,sarge_credits_created:calculateSargeCredits(actual),verified:true}));setDone(true)};
 if(done) return <Shell title="12 kWh shared." eyebrow="Contribution confirmed"><div className="success-card"><div className="success-mark"><Check/></div><h2>{actual} Sarge Credits earned.</h2><p>Your contribution is now available to the Sarge community allocation system.</p><Button onClick={()=>setDone(false)}>Share again</Button></div></Shell>;
 return <Shell title="Share your spare solar" eyebrow="Contribute"><div className="contribute-layout"><section><div className="today-flow"><div><span>Generated</span><strong>26 kWh</strong></div><ArrowRight/><div><span>Used</span><strong>14 kWh</strong></div><ArrowRight/><div className="pink"><span>Spare</span><strong>12 kWh</strong></div></div><div className="availability"><Check/><p>You currently have <strong>12 kWh of verified spare solar</strong> available.</p></div></section><section className="pledge-card"><h2>How much would you like to share?</h2>{[['all','Donate all 12 kWh'],['half','Donate 50%'],['custom','Custom amount']].map(([id,label])=><label className={`choice ${mode===id?'selected':''}`} key={id}><input type="radio" name="pledge" checked={mode===id} onChange={()=>setMode(id)}/><span>{label}</span>{mode===id&&<Check/>}</label>)}{mode==='custom'&&<div className="slider-wrap"><label htmlFor="amount">Your pledge</label><input id="amount" type="range" min="0" max="24" step="1" value={custom} onChange={e=>setCustom(e.target.value)}/><div className="number-field"><input aria-label="Custom pledge amount" type="number" min="0" value={custom} onChange={e=>setCustom(e.target.value)}/><span>kWh</span></div></div>}{pledge>spare&&<p className="cap-note">You pledged up to {pledge} kWh. You currently have 12 kWh available, so your contribution will be capped at 12 kWh.</p>}<div className="calculation"><span>Your contribution</span><strong>{actual} kWh</strong><span>Sarge Credits earned</span><strong>{calculateSargeCredits(actual)}</strong></div><Button onClick={confirm} disabled={actual<=0}>Confirm contribution <ArrowRight size={18}/></Button></section></div></Shell>;
}

function Rewards() { return <Shell title="Your contribution deserves recognition." eyebrow="Rewards"><div className="rewards-head"><div><span>Current balance</span><strong>85</strong><p>Sarge Credits</p></div><p><strong>Proposed community rewards</strong><br/>Ideas for how Sarge Credits could recognise local contribution. These are concepts, not current Wollongong City Council programs.</p></div><div className="reward-grid">{rewards.map((r,i)=><article className={`reward-card ${i===0?'featured':''}`} key={r.title}><span>{r.category}</span><h2>{r.title}</h2><p>{r.description}</p><div><strong>{r.cost} Credits</strong><Button variant={i===0?'light':'dark'}>Redeem</Button></div></article>)}</div><section className="recognition"><div><p className="eyebrow">Contributor recognition</p><h2>Silver Solar Neighbour</h2><p>A quiet thank-you for consistent community contribution.</p></div><div className="level-track"><span>Bronze</span><span className="active">Silver</span><span>Gold</span></div></section></Shell> }

function Reports() { const totals=energyHistory.reduce((a,x)=>({generated:a.generated+x.generated,used:a.used+x.used,spare:a.spare+x.spare,contributed:a.contributed+x.contributed}),{generated:0,used:0,spare:0,contributed:0}); return <Shell title="Your energy, clearly explained." eyebrow="Reports"><div className="reports-toolbar"><div><h2>Six-month report</h2><p>March–August 2026</p></div><div className="segmented">{['Monthly','Quarterly','Six months','Custom'].map((x,i)=><button className={i===2?'active':''} key={x}>{x}</button>)}</div><Button><Download size={18}/> Download report</Button></div><section className="chart-card"><h2>Generated, used and shared</h2><p className="chart-summary">Across six months, Bella generated {totals.generated} kWh, used {totals.used} kWh and contributed {totals.contributed} kWh.</p><div className="chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={energyHistory} margin={{top:20,right:10,left:-15,bottom:0}}><CartesianGrid vertical={false} stroke="#d9d9d9"/><XAxis dataKey="month" axisLine={false} tickLine={false}/><YAxis axisLine={false} tickLine={false}/><Tooltip cursor={{fill:'#f5f5f5'}}/><Legend/><Bar dataKey="generated" name="Generated" fill="#111" radius={[6,6,0,0]}/><Bar dataKey="used" name="Used" fill="#7D69E8" radius={[6,6,0,0]}/><Bar dataKey="contributed" name="Contributed" fill="#F893F6" stroke="#111" strokeWidth={1} radius={[6,6,0,0]}/></BarChart></ResponsiveContainer></div></section><h2 className="impact-title">Your six-month impact</h2><div className="impact-grid">{[['Total solar generated',totals.generated+' kWh'],['Total energy used',totals.used+' kWh'],['Total spare energy',totals.spare+' kWh'],['Total contributed',totals.contributed+' kWh'],['Sarge Credits earned',totals.contributed],['Households supported','18']].map(([l,v])=><div key={l}><span>{l}</span><strong>{v}</strong></div>)}</div></Shell> }

function Onboarding() {
 const nav=useNavigate();
 const [screen,setScreen]=useState('hero'); const [property,setProperty]=useState('Home');
 const finish=()=>{localStorage.setItem('sargeOnboardingComplete','true');localStorage.setItem('sargeOnboardingDraft',JSON.stringify({property,suburb:'Dapto',system_size_kw:6.6}));nav('/overview')};
 if(screen==='property') return <main className="property-step"><header className="property-step__nav"><div className="brand-lockup" aria-label="Sarge, Wollongong Renewable Energy Ecosystem"><img src={heroAssets.mark} alt="" className="brand-lockup__mark"/><strong className="brand-lockup__name">Sarge</strong><img src={heroAssets.divider} alt="" className="brand-lockup__divider"/><span className="brand-lockup__tag">Wollongong Renewable<br/>Energy Ecosystem</span></div><a className="button property-step__contact" href="mailto:hello@sarge.community">Contact Us</a></header><section className="property-step__card"><div className="property-step__top"><button className="property-step__back" type="button" onClick={()=>setScreen('hero')}><ChevronLeft size={22}/> Back</button><div className="property-step__progress" aria-label="Step 1 of 3"><span className="active"/><span/><span/><span/></div></div><h1>Tell us about<br/>your <em>property.</em></h1><div className="property-step__types">{donorPropertyTypes.map(([label,Icon])=><button key={label} className={property===label?'selected':''} type="button" onClick={()=>setProperty(label)}><Icon size={30}/><strong>{label}</strong>{property===label&&<Check className="property-step__check" size={22}/>}</button>)}</div><div className="property-step__form"><label><span>Property name <small>optional</small></span><input placeholder="e.g. Bella’s home"/></label><label><span>Wollongong suburb</span><select defaultValue="Dapto"><option>Dapto</option><option>Corrimal</option><option>Figtree</option><option>Port Kembla</option><option>Woonona</option></select></label><label><span>Solar system size</span><div className="property-step__number"><input defaultValue="6.6" inputMode="decimal"/><b>kW</b></div></label></div><button className="button property-step__continue" type="button" onClick={finish}>Continue <ArrowRight size={25}/></button></section></main>;
 return <main className="landing-hero"><img className="landing-hero__background" src={heroAssets.background} alt="" aria-hidden="true"/><header className="landing-hero__nav"><div className="brand-lockup" aria-label="Sarge, Wollongong Renewable Energy Ecosystem"><img src={heroAssets.mark} alt="" className="brand-lockup__mark"/><strong className="brand-lockup__name">Sarge</strong><img src={heroAssets.divider} alt="" className="brand-lockup__divider"/><span className="brand-lockup__tag">Wollongong Renewable<br/>Energy Ecosystem</span></div><a className="button button--contact" href="mailto:hello@sarge.community">Contact Us</a></header><img className="landing-hero__illustration" src={heroAssets.family} alt="" aria-hidden="true"/><section className="landing-hero__content"><h1>Share the sun,<br/>with <em>The Gong.</em></h1><p>Sarge lets you contribute solar energy you don’t use to support Wollongong households experiencing energy hardship — while recognising you for helping.</p><div className="landing-hero__actions"><button className="button button--hero" type="button" onClick={()=>setScreen('property')}>Get Started <ArrowRight size={26}/></button><a className="button button--mobile-contact" href="mailto:hello@sarge.community">Contact Us</a></div></section></main>;
}

function RootRedirect(){const done=typeof window!=='undefined'&&localStorage.getItem('sargeOnboardingComplete')==='true'; return <Navigate to={done?'/overview':'/onboarding'} replace/>}
function useIsClient(){return useSyncExternalStore(()=>()=>{},()=>true,()=>false)}
export default function App(){const isClient=useIsClient();if(!isClient)return <main className="app-boot" aria-label="Loading Sarge"/>;return <BrowserRouter><Routes><Route path="/" element={<RootRedirect/>}/><Route path="/onboarding" element={<Onboarding/>}/><Route path="/overview" element={<Overview/>}/><Route path="/contribute" element={<Contribute/>}/><Route path="/rewards" element={<Rewards/>}/><Route path="/reports" element={<Reports/>}/><Route path="/council" element={<CouncilDashboard/>}/><Route path="/council/*" element={<CouncilDashboard/>}/><Route path="*" element={<Navigate to="/" replace/>}/></Routes></BrowserRouter>}
